-- AlterTable
ALTER TABLE "SystemConfig" ADD COLUMN     "priceBronze" DOUBLE PRECISION DEFAULT 119.90,
ADD COLUMN     "priceGold" DOUBLE PRECISION DEFAULT 169.90,
ADD COLUMN     "priceSilver" DOUBLE PRECISION DEFAULT 139.90;
